### ISSUE TITLE
mosaic — explain what's wrong if the images have no WCS

### ISSUE THREAD

**Issue by vterron** [vterron/lemon#43]
If none of the FITS images given to `mosaic` have WCS information in their headers (in other words, if they have not been astrometrically solved), the error message (`mMakeHdr: Invalid table file`) is rather confusing and makes it almost impossible, particularly for a novice, to understand what may be failing:

    vterron@iaa:~/ngc2264$ lemon mosaic ferM_005* ngc2264-mosaic.fits
    >> Making sure the 10 input paths are FITS images...
    >> 100%[======================================================================>]
    INFO: Listing raw frames [montage_wrapper.wrappers]
    INFO: Computing optimal header [montage_wrapper.wrappers]
    Traceback (most recent call last):
      File "/home/vterron/lemon/lemon", line 136, in <module>
        module.main(args)
      File "/home/vterron/lemon/mosaic.py", line 257, in main
        montage.mosaic(input_dir, output_dir, **kwargs)
      File "/home/vterron/.local/lib/python2.7/site-packages/montage_wrapper/wrappers.py", line 534, in mosaic
        m.mMakeHdr(images_raw_all_tbl, header_hdr)
      File "/home/vterron/.local/lib/python2.7/site-packages/montage_wrapper/commands.py", line 1468, in mMakeHdr
        return status.parse_struct("mMakeHdr", p.stdout.read().strip())
      File "/home/vterron/.local/lib/python2.7/site-packages/montage_wrapper/status.py", line 33, in parse_struct
        result = Struct(command, string)
      File "/home/vterron/.local/lib/python2.7/site-packages/montage_wrapper/status.py", line 70, in __init__
        raise MontageError("%s: %s" % (command, self.msg))
    montage_wrapper.status.MontageError: mMakeHdr: Invalid table file: /tmp/montage_mosaic_tmpqIGPiH_LEMON_26615_mosaic_input_ipM_2B/images_raw_all.tbl
    INFO: Deleting work directory /tmp/montage_mosaic_tmpqIGPiH_LEMON_26615_mosaic_input_ipM_2B [montage_wrapper.wrappers]
    vterron@iaa:~/ngc2264$

This should be improved, ideally explaining to the user that `astrometry` must be run first.

**Comment by vterron** [comment]
Done in b16a9bf.
