### ISSUE TITLE
astrometry freezing

### ISSUE THREAD

**Issue by paramoreta** [vterron/lemon#44]
Hey,
Astrometry utility seems to freeze despite the arguments seem valid (according to the command description). 
I enter the command and specify the cores to 1 to avoid [the known bug](https://github.com/astropy/montage-wrapper/issues/18). It doesn't really matter because it happens the same with the cores down to 8 (i.e., no `--cores` option specified).

Note that after a couple of minutes, I pressed Ctrl+C to stop the process:

```
louis@ck:~/Desktop/optical/INT/test$ lemon astrometry --cores=1 shit* .
>> Images will be saved to directory '.'
>> Using a local build of Astrometry.net.
>> Doing astrometry on the 4 paths given as input.
>> 0%[>                                                                        ]
^C
Traceback (most recent call last):
  File "/home/louis/Desktop/work/routines/lemon/lemon", line 136, in <module>
    module.main(args)
  File "/home/louis/Desktop/work/routines/lemon/astrometry.py", line 490, in main
    time.sleep(1)
KeyboardInterrupt
Process PoolWorker-1:
Traceback (most recent call last):
  File "/usr/lib/python2.7/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/usr/lib/python2.7/multiprocessing/process.py", line 114, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/lib/python2.7/multiprocessing/pool.py", line 96, in worker
    result = (True, func(*args, **kwds))
  File "/usr/lib/python2.7/multiprocessing/pool.py", line 65, in mapstar
    return map(*args)
  File "/home/louis/Desktop/work/routines/lemon/methods.py", line 615, in wrapper
    return func(*args, **kwargs)
  File "/home/louis/Desktop/work/routines/lemon/astrometry.py", line 322, in parallel_astrometry
    output_path = astrometry_net(img.path, **kwargs)
  File "/home/louis/Desktop/work/routines/lemon/astrometry.py", line 238, in astrometry_net
    subprocess.check_call(args, **kwargs)
  File "/home/louis/.local/lib/python2.7/site-packages/subprocess32.py", line 594, in check_call
    retcode = call(*popenargs, **kwargs)
  File "/home/louis/.local/lib/python2.7/site-packages/subprocess32.py", line 577, in call
    return p.wait(timeout=timeout)
  File "/home/louis/.local/lib/python2.7/site-packages/subprocess32.py", line 1678, in wait
    time.sleep(delay)
KeyboardInterrupt
```

**Comment by vterron** [comment]
Please run the same command with the `-v` option, so that you can see the output of Astrometry.net. My first guess is that everything is working fine but these images are taking too long to solve — this happens, for example, if they do not have their approximate coordinates in the `RA` and `DEC` keywords.

**Comment by vterron** [comment]
I should add that `--cores=1` is only necessary with the `mosaic` command (which uses the `montage-wrapper` module). The `astrometry` command should always work regardless of the number of processes, although there are some scenarios (namely, if you have too many CPUs and a not-that-fast hard drive) where performance can be improved if the number is decreased.

**Comment by paramoreta** [comment]
Well, it all pretty much solved everything. As you said, there was no freezing (hadn't provided RA and DEC).
And also, thanks for the input on the '''--cores''' option, at some point, I mistakenly thought the bug involved both mosaic and astrometry! My bad.

**Comment by vterron** [comment]
Don't worry at all. The mistake is mostly our fault, as there would be little room for such misunderstandings if we had a proper documentation up and running, as we ought to. Please let us know if you come across something amiss or that you do not fully understand! Thanks!
