### ISSUE TITLE
mosaic: contradiction in "--filter" option

### ISSUE THREAD

**Issue by paramoreta** [vterron/lemon#46]
When using ```mosaic``` task to make a single image out of several fits (22 in this case, but irrelevant), providing the ```filter``` option is unnecessary, according to the documentation. However, I am getting an error message in which I am asked to provide it anyway.
Here it is:

```
>> Making sure the 22 input paths are FITS images...
>> 0%[>                                                                        ]Traceback (most recent call last):
  File "/home/louisck/Desktop/work/routines/lemon/lemon", line 136, in <module>
    module.main(args)
  File "/home/louisck/Desktop/work/routines/lemon/mosaic.py", line 175, in main
    pfilter = img.pfilter(options.filterk)
  File "/home/louisck/Desktop/work/routines/lemon/fitsimage.py", line 487, in pfilter
    pfilter_str = self.read_keyword(keyword)
  File "/home/louisck/Desktop/work/routines/lemon/fitsimage.py", line 173, in read_keyword
    raise KeyError(msg)
KeyError: "cig0340_20140101_R_022-b-sf-bfa.fits: keyword 'FILTER' not found"
```

**Comment by vterron** [comment]
Fixed in 3c8b08c. Thanks a lot.
