### ISSUE TITLE
mosaic does not recognize WCS header?

### ISSUE THREAD

**Issue by ubutnux** [vterron/lemon#64]
all the FITS images have WCS header from astrometry 
```
ucup@ubuntu:~$ lemon mosaic eh-lib/*.fts tes-mos.fit
>> Making sure the 2 input paths are FITS images...
>> 100%[======================================================================>]
INFO: Listing raw frames [montage_wrapper.wrappers]
INFO: Computing optimal header [montage_wrapper.wrappers]
Traceback (most recent call last):
  File "/home/ucup/lemon/lemon", line 135, in <module>
    module.main(args)
  File "/home/ucup/lemon/mosaic.py", line 304, in main
    montage.mosaic(input_dir, output_dir, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/montage_wrapper/wrappers.py", line 534, in mosaic
    m.mMakeHdr(images_raw_all_tbl, header_hdr)
  File "/usr/local/lib/python2.7/dist-packages/montage_wrapper/commands.py", line 1468, in mMakeHdr
    return status.parse_struct("mMakeHdr", p.stdout.read().strip())
  File "/usr/local/lib/python2.7/dist-packages/montage_wrapper/status.py", line 33, in parse_struct
    result = Struct(command, string)
  File "/usr/local/lib/python2.7/dist-packages/montage_wrapper/status.py", line 70, in __init__
    raise MontageError("%s: %s" % (command, self.msg))
montage_wrapper.status.MontageError: mMakeHdr: Invalid table file: /tmp/montage_mosaic_tmp4Pgy9o_LEMON_28370_mosaic_input_2TNWuq/images_raw_all.tbl
INFO: Deleting work directory /tmp/montage_mosaic_tmp4Pgy9o_LEMON_28370_mosaic_input_2TNWuq [montage_wrapper.wrappers]
```

this is the header
```
COMMENT --Start of Astrometry.net WCS solution--                                
COMMENT --Put in by the new-wcs program--                                       
COMMENT                                                                         
WCSAXES =                    2 / no comment                                     
CTYPE1  = 'RA---TAN-SIP' / TAN (gnomic) projection + SIP distortions            
CTYPE2  = 'DEC--TAN-SIP' / TAN (gnomic) projection + SIP distortions            
EQUINOX =               2000.0 / Equatorial coordinates definition (yr)         
LONPOLE =                180.0 / no comment                                     
LATPOLE =                  0.0 / no comment                                     
CRVAL1  =        224.777250672 / RA  of reference point                         
CRVAL2  =      -0.945480721722 / DEC of reference point                         
CRPIX1  =         2033.9175415 / X reference pixel                              
CRPIX2  =        2269.25918579 / Y reference pixel                              
CUNIT1  = 'deg     ' / X pixel scale units                                      
CUNIT2  = 'deg     ' / Y pixel scale units                                      
CD1_1   =    4.22228778718E-06 / Transformation matrix                          
CD1_2   =    0.000201267285409 / no comment                                     
CD2_1   =   -0.000201259711753 / no comment                                     
CD2_2   =    4.15822740946E-06 / no comment                                     
IMAGEW  =                 4096 / Image width,  in pixels.                       
IMAGEH  =                 4096 / Image height, in pixels.                       
A_ORDER =                    2 / Polynomial order, axis 1                       
A_0_0   =                    0 / no comment                                     
A_0_1   =                    0 / no comment                                     
A_0_2   =   -1.35578367059E-07 / no comment                                     
A_1_0   =                    0 / no comment                                     
A_1_1   =   -2.18497567051E-07 / no comment                                     
A_2_0   =   -5.14143366522E-08 / no comment                                     
B_ORDER =                    2 / Polynomial order, axis 2                       
B_0_0   =                    0 / no comment                                     
B_0_1   =                    0 / no comment                                     
B_0_2   =   -2.41432917051E-07 / no comment                                     
B_1_0   =                    0 / no comment                                     
B_1_1   =   -1.83611518229E-07 / no comment                                     
B_2_0   =   -1.69373154503E-07 / no comment                                     
AP_ORDER=                    2 / Inv polynomial order, axis 1                   
AP_0_0  =    9.07391373255E-05 / no comment                                     
AP_0_1  =    4.21174643868E-07 / no comment                                     
AP_0_2  =    1.35517414024E-07 / no comment                                     
AP_1_0  =    3.51582683238E-07 / no comment                                     
AP_1_1  =    2.18428163006E-07 / no comment                                     
AP_2_0  =    5.13895010485E-08 / no comment                                     
BP_ORDER=                    2 / Inv polynomial order, axis 2                   
BP_0_0  =    0.000142932769025 / no comment                                     
BP_0_1  =    6.57540940404E-07 / no comment                                     
BP_0_2  =    2.41341878341E-07 / no comment                                     
BP_1_0  =    4.47959198235E-07 / no comment                                     
BP_1_1  =    1.83520046971E-07 / no comment                                     
BP_2_0  =    1.69330994199E-07 / no comment                                     
HISTORY Created by the Astrometry.net suite.                                    
HISTORY For more details, see http://astrometry.net.                            
HISTORY Git URL https://github.com/dstndstn/astrometry.net                      
HISTORY Git revision 0.55                                                       
HISTORY Git date Thu_May_14_17:25:20_2015_+0000                                 
HISTORY This WCS header was created by the program "blind".                     
HISTORY Astrometry done via LEMON on Tue Jun 23 22:44:11 2015 UTC               
HISTORY [Astrometry] WCS solution found by Astrometry.net                       
HISTORY [Astrometry] Original image: data/ehlib-S001-R001-C001-V.fts            
DATE    = '2015-06-23T15:44:11' / Date this file was created.                   
COMMENT -- blind solver parameters: --                                          
COMMENT Index(0): /home/ucup/astrometry-index/index-4207-11.fits                
COMMENT Index(1): /home/ucup/astrometry-index/index-4207-10.fits                
COMMENT Index(2): /home/ucup/astrometry-index/index-4207-09.fits                
COMMENT Index(3): /home/ucup/astrometry-index/index-4207-08.fits                
COMMENT Index(4): /home/ucup/astrometry-index/index-4207-07.fits                
COMMENT Index(5): /home/ucup/astrometry-index/index-4207-06.fits                
COMMENT Index(6): /home/ucup/astrometry-index/index-4207-05.fits                
COMMENT Index(7): /home/ucup/astrometry-index/index-4207-04.fits                
COMMENT Index(8): /home/ucup/astrometry-index/index-4207-03.fits                
COMMENT Index(9): /home/ucup/astrometry-index/index-4207-02.fits                
COMMENT Index(10): /home/ucup/astrometry-index/index-4207-01.fits               
COMMENT Index(11): /home/ucup/astrometry-index/index-4207-00.fits               
COMMENT Index(12): /home/ucup/astrometry-index/index-4206-11.fits               
COMMENT Index(13): /home/ucup/astrometry-index/index-4206-10.fits               
COMMENT Index(14): /home/ucup/astrometry-index/index-4206-09.fits               
COMMENT Index(15): /home/ucup/astrometry-index/index-4206-08.fits               
COMMENT Index(16): /home/ucup/astrometry-index/index-4206-07.fits               
COMMENT Index(17): /home/ucup/astrometry-index/index-4206-06.fits               
COMMENT Index(18): /home/ucup/astrometry-index/index-4206-05.fits               
COMMENT Index(19): /home/ucup/astrometry-index/index-4206-04.fits               
COMMENT Index(20): /home/ucup/astrometry-index/index-4206-03.fits               
COMMENT Index(21): /home/ucup/astrometry-index/index-4206-02.fits               
COMMENT Index(22): /home/ucup/astrometry-index/index-4206-01.fits               
COMMENT Index(23): /home/ucup/astrometry-index/index-4206-00.fits               
COMMENT Index(24): /home/ucup/astrometry-index/index-4205-11.fits               
COMMENT Index(25): /home/ucup/astrometry-index/index-4205-10.fits               
COMMENT Index(26): /home/ucup/astrometry-index/index-4205-09.fits               
COMMENT Index(27): /home/ucup/astrometry-index/index-4205-08.fits               
COMMENT Index(28): /home/ucup/astrometry-index/index-4205-07.fits               
COMMENT Index(29): /home/ucup/astrometry-index/index-4205-06.fits               
COMMENT Index(30): /home/ucup/astrometry-index/index-4205-05.fits               
COMMENT Index(31): /home/ucup/astrometry-index/index-4205-04.fits               
COMMENT Index(32): /home/ucup/astrometry-index/index-4205-03.fits               
COMMENT Index(33): /home/ucup/astrometry-index/index-4205-02.fits               
COMMENT Index(34): /home/ucup/astrometry-index/index-4205-01.fits               
COMMENT Index(35): /home/ucup/astrometry-index/index-4205-00.fits               
COMMENT Field name:                                                             
COMMENT   /tmp/ehlib-S001-R001-C001-V_44mYCD_astrometry.net/ehlib-S0            
COMMENT   01-R001-C001-V.axy                                                    
COMMENT Field scale lower: 0.0878906 arcsec/pixel                               
COMMENT Field scale upper: 158.203 arcsec/pixel                                 
COMMENT X col name: X                                                           
COMMENT Y col name: Y                                                           
COMMENT Start obj: 0                                                            
COMMENT End obj: 10                                                             
COMMENT Solved_in: (null)                                                       
COMMENT Solved_out:                                                             
COMMENT   /tmp/ehlib-S001-R001-C001-V_44mYCD_astrometry.net/ehlib-S0            
COMMENT   01-R001-C001-V.solved                                                 
COMMENT Solvedserver: (null)                                                    
COMMENT Parity: 2                                                               
COMMENT Codetol: 0.01                                                           
COMMENT Verify pixels: 1 pix                                                    
COMMENT Maxquads: 0                                                             
COMMENT Maxmatches: 0                                                           
COMMENT Cpu limit: 300.000000 s                                                 
COMMENT Time limit: 0 s                                                         
COMMENT Total time limit: 0 s                                                   
COMMENT Total CPU limit: 300.000000 s                                           
COMMENT Tweak: yes                                                              
COMMENT Tweak AB order: 2                                                       
COMMENT Tweak ABP order: 2                                                      
COMMENT --                                                                      
COMMENT -- properties of the matching quad: --                                  
COMMENT index id: 4207                                                          
COMMENT index healpix: 10                                                       
COMMENT index hpnside: 1                                                        
COMMENT log odds: 401.034                                                       
COMMENT odds: 1.46816e+174                                                      
COMMENT quadno: 277161                                                          
COMMENT stars: 143443,143491,143497,143493                                      
COMMENT field: 3,7,9,8                                                          
COMMENT code error: 0.00154222                                                  
COMMENT nmatch: 48                                                              
COMMENT nconflict: 0                                                            
COMMENT nfield: 817                                                             
COMMENT nindex: 50                                                              
COMMENT scale: 0.724706 arcsec/pix                                              
COMMENT parity: 1                                                               
COMMENT quads tried: 102                                                        
COMMENT quads matched: 8                                                        
COMMENT quads verified: 7                                                       
COMMENT objs tried: 10                                                          
COMMENT cpu time: 0.001067                                                      
COMMENT --                                                                      
COMMENT                                                                         
COMMENT --End of Astrometry.net WCS--                                           
COMMENT --(Put in by the new-wcs program)--                                     
COMMENT                                                                         
```

astrometry version 0.55
lemon version v0.3-21-g2585cd0

**Comment by jorgegocre** [comment]
Something very similar has happen to me too.


>> Making sure the 5 input paths are FITS images...
>> 100%[======================================================================>]
INFO: Listing raw frames [montage_wrapper.wrappers]
INFO: Computing optimal header [montage_wrapper.wrappers]
Traceback (most recent call last):
  File "/opt/cesga//lemon-0.2.0/lemon", line 136, in <module>
    module.main(args)
  File "/mnt/EMC/Optcesga_SVG/opt/cesga/lemon-0.2.0/mosaic.py", line 302, in main
    montage.mosaic(input_dir, output_dir, **kwargs)
  File "/opt/cesga/python2/python-2.7.3/build/lib/python2.7/site-packages/montage_wrapper/wrappers.py", line 534, in mosaic
    m.mMakeHdr(images_raw_all_tbl, header_hdr)
  File "/opt/cesga/python2/python-2.7.3/build/lib/python2.7/site-packages/montage_wrapper/commands.py", line 1468, in mMakeHdr
    return status.parse_struct("mMakeHdr", p.stdout.read().strip())
  File "/opt/cesga/python2/python-2.7.3/build/lib/python2.7/site-packages/montage_wrapper/status.py", line 33, in parse_struct
    result = Struct(command, string)
  File "/opt/cesga/python2/python-2.7.3/build/lib/python2.7/site-packages/montage_wrapper/status.py", line 70, in __init__
    raise MontageError("%s: %s" % (command, self.msg))
montage_wrapper.status.MontageError: mMakeHdr: Invalid table file: /scratch/2571757.1.interactive/montage_mosaic_tmpKikSYC_LEMON_7697_mosaic_input_6vffRY/images_raw_all.tbl
INFO: Deleting work directory /scratch/2571757.1.interactive/montage_mosaic_tmpKikSYC_LEMON_7697_mosaic_input_6vffRY [montage_wrapper.wrappers]

**Comment by ubutnux** [comment]
I solved the issue. Looks like it's the file format is the problem. our robotic telescope use '.fts'. Just make sure the file is in 'fit' or 'fits' format, and fix the header.

**Comment by jorgegocre** [comment]
I also use .fts, I will try

**Comment by jorgegocre** [comment]
What do you mean with fix the header? add /end?¿ after comments?

**Comment by jorgegocre** [comment]
Done, it works.

**Comment by vterron** [comment]
Thanks, ubutnux.
