### ISSUE TITLE
ConfigParser.ParsingError: File contains parsing errors: /home/usc/oa/jgc/.lemonrc

### ISSUE THREAD

**Issue by jorgegocre** [vterron/lemon#65]
```
[uscoajgc@compute-4-2 ~]$ lemon photometry -vvv LEM1/LEMmosaic.fits LEM1/LEM/*.fits LEMphot.LEMONdB
Traceback (most recent call last):
  File "/opt/cesga//lemon-0.2.0/lemon", line 135, in <module>
    module = __import__(command)
  File "/mnt/EMC/Optcesga_SVG/opt/cesga/lemon-0.2.0/photometry.py", line 61, in <module>
    import customparser
  File "/mnt/EMC/Optcesga_SVG/opt/cesga/lemon-0.2.0/customparser.py", line 27, in <module>
    import passband
  File "/mnt/EMC/Optcesga_SVG/opt/cesga/lemon-0.2.0/passband.py", line 100, in <module>
    CUSTOM_FILTERS = dict(load_custom_filters())
  File "/mnt/EMC/Optcesga_SVG/opt/cesga/lemon-0.2.0/passband.py", line 79, in load_custom_filters
    parser.read([path])
  File "/opt/cesga/python2/python-2.7.3/build/lib/python2.7/ConfigParser.py", line 305, in read
    self._read(fp, filename)
  File "/opt/cesga/python2/python-2.7.3/build/lib/python2.7/ConfigParser.py", line 546, in _read
    raise e
ConfigParser.ParsingError: File contains parsing errors: /home/usc/oa/jgc/.lemonrc
    [line  2]: ' GG475 = J (Yellow Schott Filter)\n'
```

**Comment by vterron** [comment]
Can you please paste here your `.lemonrc` file, so that I can try to reproduce the error?

**Comment by jorgegocre** [comment]
I also notice that when I wrote here my lemonrc with the space before GG475, the page directly realigned it with [ 

[custom_filters]
_GG475 = J (Yellow Schott Filter)

I will repeat it with a space character instead of the low line as above:

[custom_filters]
 GG475 = J (Yellow Schott Filter)

**Comment by jorgegocre** [comment]
Solved. 

The problem is not about lemon or .lemonrc, the problem was the format of the filter name on my original .fts, it came with 13 spaces before the filter name, I had changed it and now works as it has to work.
