### ISSUE TITLE
VerifyError: Unparsable card (RA), fix it first with .verify('fix')

### ISSUE THREAD

**Issue by sameerprl** [vterron/lemon#68]
Hi vterron following error is encountered : 

    sameer@sameer-HP-406-G1-MT:~/Desktop/1HOpt$ lemon astrometry *.fits 1H/
    >> The output directory '1H/' did not exist, so it had to be created.
    >> Using a local build of Astrometry.net.
    >> Doing astrometry on the 2 paths given as input.
    Traceback (most recent call last):
    Traceback (most recent call last):
      File "/home/sameer/lemon/methods.py", line 592, in wrapper
      File "/home/sameer/lemon/methods.py", line 592, in wrapper
        return func(*args, **kwargs)
        return func(*args, **kwargs)
      File "/home/sameer/lemon/astrometry.py", line 303, in parallel_astrometry
      File "/home/sameer/lemon/astrometry.py", line 303, in parallel_astrometry
        ra  = img.ra (options.rak)
        ra  = img.ra (options.rak)
      File "/home/sameer/lemon/fitsimage.py", line 526, in ra
      File "/home/sameer/lemon/fitsimage.py", line 526, in ra
        ra_str = self.read_keyword(ra_keyword)
        ra_str = self.read_keyword(ra_keyword)
      File "/home/sameer/lemon/fitsimage.py", line 190, in read_keyword
      File "/home/sameer/lemon/fitsimage.py", line 190, in read_keyword
        return self._header[keyword.upper()]
        return self._header[keyword.upper()]
      File "/usr/local/lib/python2.7/dist-packages/pyfits/header.py", line
    148, in __getitem__
      File "/usr/local/lib/python2.7/dist-packages/pyfits/header.py", line
    148, in __getitem__
        return card.value
        return card.value
      File "/usr/local/lib/python2.7/dist-packages/pyfits/card.py", line 543,
    in value
      File "/usr/local/lib/python2.7/dist-packages/pyfits/card.py", line 543,
    in value
        self._value = self._parse_value()
        self._value = self._parse_value()
      File "/usr/local/lib/python2.7/dist-packages/pyfits/card.py", line 1011,
    in _parse_value
      File "/usr/local/lib/python2.7/dist-packages/pyfits/card.py", line 1011,
    in _parse_value
        ".verify('fix')." % self.keyword)
        ".verify('fix')." % self.keyword)
    VerifyError: Unparsable card (RA), fix it first with .verify('fix').
    VerifyError: Unparsable card (RA), fix it first with .verify('fix').

    >> 0%[>
        ]Traceback (most recent call last):
      File "/home/sameer/lemon/lemon", line 135, in <module>
        module.main(args)
      File "/home/sameer/lemon/astrometry.py", line 499, in main
        result.get() # reraise exceptions of the remote call, if any
      File "/usr/lib/python2.7/multiprocessing/pool.py", line 558, in get
        raise self._value
    pyfits.verify.VerifyError: Unparsable card (RA), fix it first with
    .verify('fix').

**Comment by vterron** [comment]
It looks like your images do not conform to the [FITS standard](http://fits.gsfc.nasa.gov/fits_standard.html), as it is required — not directly by us, but by the underlying libraries that we use. Please use a tool such as [FITS File Verifier](http://fits.gsfc.nasa.gov/fits_verify.html) to check if that is the case and, if so, fix them.

**Comment by sameerprl** [comment]
Thanks resolved !

**Comment by Pratikdomadiya** [comment]
Unparsable card (GWILL), fix it first with .verify('fix'). can you help me to fix this error,please

**Comment by vterron** [comment]
Please see [the message above](https://github.com/vterron/lemon/issues/68#issuecomment-176966958). Your FITS image most likely doesn't follow the FITS standard.
