### ISSUE TITLE
ValueError: Parameter dannulus: value `0.xxx' is less than minimum `1.0'

### ISSUE THREAD

**Issue by sameeresque** [vterron/lemon#78]
I encounter this error,I couldn't locate where the setting for minimum value is done, could you comment?

**Comment by vterron** [comment]
That would be the [--min-sky option](https://github.com/vterron/lemon/blob/master/photometry.py#L358) of `photometry`.

What command were you using, and what was the full output?

**Comment by StuartLittlefair** [comment]
I think I have also encountered this issue; when running with ```--individual-fwhm``` set, ```lemon``` no longer seems to apply the ```--min-sky``` option, and ```dannulus``` is too small. 

Running the command

```
lemon photometry --overwrite --individual-fwhm --gaink=EGAIN --aperture=1.7 --annulus=2.5 --min-sky=3 mosaic_r.fits r0320*s.fits small_aperture_individual.LEMONdB
```

I get the following output:

```python
>> Examining the headers of the 58 FITS files given as input...
>> 100%[======================================================================>]
>> 3 different photometric filters were detected:
>>  B: 3 files (5.17 %)
>>  V: 3 files (5.17 %)
>>  R: 52 files (89.66 %)
>> Making sure there are no images with the same date and filter... done.
>> Sources image: mosaic_r.fits
>> Running SExtractor on the sources image... done.
>> Calculating coordinates of field center... done.
>> α = 290.3520378  (19 21 24.49)
>> δ =  -4.1599424 (-04 09 35.79)
>> Detected 2387 sources on which to do photometry.
>> 
>> Need to determine the instrumental magnitude of each source.
>> Doing photometry on the sources image, using the parameters:
>> FWHM (sources image) = 6.239 pixels, therefore:
>> Aperture radius = 6.239 x 1.70 = 10.606 pixels
>> Sky annulus, inner radius = 6.239 x 2.50 = 15.598 pixels
>> Sky annulus, width = 6.239 x 1.00 = 6.239 pixels
>> 
>> Running IRAF's qphot... done.
>> Detecting INDEF objects... done.
>> 386 objects are INDEF in the sources image.
>> There are 2001 objects left on which to do photometry.
>> Making sure INDEF objects were removed... done.
>> 
>> Initializing output LEMONdB... done.
>> 
>> Let's do photometry on the 3 images taken in the B filter.
>> Using parameters derived from the FWHM of each image:
>> Aperture radius = 1.70 x FWHM pixels
>> Sky annulus, inner radius = 2.50 x FWHM pixels
>> Sky annulus, width = 1.00 x FWHM pixels
>> 0%[>                                                                        ]Traceback (most recent call last):
  File "/home/pha14lr/lemon/methods.py", line 592, in wrapper
    return func(*args, **kwargs)
  File "/home/pha14lr/lemon/photometry.py", line 183, in parallel_photometry
    img_qphot = qphot.run(*args, cbox=options.cbox)
  File "/home/pha14lr/lemon/qphot.py", line 598, in run
    img_qphot.run(annulus, dannulus, aperture, exptimek, cbox=cbox)
  File "/home/pha14lr/lemon/qphot.py", line 334, in run
    apphot.qphot(self.path, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/pyraf/iraftask.py", line 767, in __call__
    return self.run(*args, **kw)
  File "/usr/local/lib/python2.7/dist-packages/pyraf/iraftask.py", line 342, in run
    self.setParList(*args, **kw)
  File "/usr/local/lib/python2.7/dist-packages/pyraf/iraftask.py", line 460, in setParList
    newParList.setParList(*args, **kw)
  File "/usr/local/lib/python2.7/dist-packages/pyraf/irafpar.py", line 990, in setParList
    p.set(value)
  File "/usr/local/lib/python2.7/dist-packages/stsci/tools/basicpar.py", line 392, in set
    self.value = self.checkValue(value)
  File "/usr/local/lib/python2.7/dist-packages/stsci/tools/basicpar.py", line 405, in checkValue
    return self.checkOneValue(v,strict)
  File "/usr/local/lib/python2.7/dist-packages/stsci/tools/basicpar.py", line 429, in checkOneValue
    (self.name, str(v), str(self.min)))
ValueError: Parameter dannulus: value `0.874' is less than minimum `1.0'

Traceback (most recent call last):
  File "/home/pha14lr/lemon/methods.py", line 592, in wrapper
    return func(*args, **kwargs)
  File "/home/pha14lr/lemon/photometry.py", line 183, in parallel_photometry
    img_qphot = qphot.run(*args, cbox=options.cbox)
  File "/home/pha14lr/lemon/qphot.py", line 598, in run
    img_qphot.run(annulus, dannulus, aperture, exptimek, cbox=cbox)
  File "/home/pha14lr/lemon/qphot.py", line 334, in run
    apphot.qphot(self.path, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/pyraf/iraftask.py", line 767, in __call__
    return self.run(*args, **kw)
  File "/usr/local/lib/python2.7/dist-packages/pyraf/iraftask.py", line 342, in run
    self.setParList(*args, **kw)
  File "/usr/local/lib/python2.7/dist-packages/pyraf/iraftask.py", line 460, in setParList
    newParList.setParList(*args, **kw)
  File "/usr/local/lib/python2.7/dist-packages/pyraf/irafpar.py", line 990, in setParList
    p.set(value)
  File "/usr/local/lib/python2.7/dist-packages/stsci/tools/basicpar.py", line 392, in set
    self.value = self.checkValue(value)
  File "/usr/local/lib/python2.7/dist-packages/stsci/tools/basicpar.py", line 405, in checkValue
    return self.checkOneValue(v,strict)
  File "/usr/local/lib/python2.7/dist-packages/stsci/tools/basicpar.py", line 429, in checkOneValue
    (self.name, str(v), str(self.min)))
ValueError: Parameter dannulus: value `0.863' is less than minimum `1.0'

Traceback (most recent call last):
  File "/home/pha14lr/lemon/methods.py", line 592, in wrapper
    return func(*args, **kwargs)
  File "/home/pha14lr/lemon/photometry.py", line 183, in parallel_photometry
    img_qphot = qphot.run(*args, cbox=options.cbox)
  File "/home/pha14lr/lemon/qphot.py", line 598, in run
    img_qphot.run(annulus, dannulus, aperture, exptimek, cbox=cbox)
  File "/home/pha14lr/lemon/qphot.py", line 334, in run
    apphot.qphot(self.path, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/pyraf/iraftask.py", line 767, in __call__
    return self.run(*args, **kw)
  File "/usr/local/lib/python2.7/dist-packages/pyraf/iraftask.py", line 342, in run
    self.setParList(*args, **kw)
  File "/usr/local/lib/python2.7/dist-packages/pyraf/iraftask.py", line 460, in setParList
    newParList.setParList(*args, **kw)
  File "/usr/local/lib/python2.7/dist-packages/pyraf/irafpar.py", line 990, in setParList
    p.set(value)
  File "/usr/local/lib/python2.7/dist-packages/stsci/tools/basicpar.py", line 392, in set
    self.value = self.checkValue(value)
  File "/usr/local/lib/python2.7/dist-packages/stsci/tools/basicpar.py", line 405, in checkValue
    return self.checkOneValue(v,strict)
  File "/usr/local/lib/python2.7/dist-packages/stsci/tools/basicpar.py", line 429, in checkOneValue
    (self.name, str(v), str(self.min)))
ValueError: Parameter dannulus: value `0.874' is less than minimum `1.0'

>> 0%[>                                                                        ]Traceback (most recent call last):
  File "/home/pha14lr/lemon/lemon", line 135, in <module>
    module.main(args)
  File "/home/pha14lr/lemon/photometry.py", line 1411, in main
    result.get() # reraise exceptions of the remote call, if any
  File "/usr/lib/python2.7/multiprocessing/pool.py", line 558, in get
    raise self._value
ValueError: Parameter dannulus: value `0.874' is less than minimum `1.0'
```
