### ISSUE TITLE
"OSError: [Errno 2] No such file or directory" on lemon mosaic

### ISSUE THREAD

**Issue by cdilga** [vterron/lemon#88]
Hi,

```
cdilga@RED-GOD-UBUNTU:~/Documents/m101$ lemon mosaic lemon-out/*.fits output.fits
>> Making sure the 10 input paths are FITS images...
>> 100%[======================================================================>]
INFO: Listing raw frames [montage_wrapper.wrappers]
INFO: Computing optimal header [montage_wrapper.wrappers]
INFO: Projecting raw frames [montage_wrapper.wrappers]
Traceback (most recent call last):
  File "/home/cdilga/lemon/lemon", line 135, in <module>
    module.main(args)
  File "/home/cdilga/lemon/mosaic.py", line 304, in main
    montage.mosaic(input_dir, output_dir, **kwargs)
  File "/home/cdilga/.local/lib/python2.7/site-packages/montage_wrapper/wrappers.py", line 552, in mosaic
    raw_dir=raw_dir, mpi=mpi, n_proc=n_proc, exact=exact_size)
  File "/home/cdilga/.local/lib/python2.7/site-packages/montage_wrapper/commands.py", line 1833, in mProjExec
    stderr=subprocess.PIPE)
  File "/usr/lib/python2.7/subprocess.py", line 710, in __init__
    errread, errwrite)
  File "/usr/lib/python2.7/subprocess.py", line 1335, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory
INFO: Deleting work directory /tmp/montage_mosaic_tmp2lbtOv_LEMON_23858_mosaic_input_IjnGzL [montage_wrapper.wrappers]
```

Any suggestions for how to fix this problem?

**Comment by vterron** [comment]
Did you [enable them when you installed Montage](http://lemon.readthedocs.io/en/latest/user/install.html#id4)? Does the error disappear if you try running the command with the `--cores=1` option.

**Comment by cdilga** [comment]
Cheers, --cores=1 allows the command to complete successfully.
I have double checked, and the two lines are definitely uncommented. Perhaps somehow Montage still didn't include MPI. Any ideas on checking this?

**Comment by vterron** [comment]
What's the output in you run `which mAddMPI` in a terminal?

Kind of a silly question, but are you using Linux? If that's not the case, maybe on your platform (Mac OS?) Montage is not using that Makefile when the binaries are compiled?

**Comment by cdilga** [comment]
I am using Ubuntu Linux, and I am modifying the Makefile.LINUX, but It does look like it's not compiling with MPI. This can't be a lemon issue. Here is the output of mAddMPI:

```
cdilga@RED-GOD-UBUNTU:~/Programs/Montage$ mAddMPI
[RED-GOD-UBUNTU:17390] [[INVALID],INVALID] ORTE_ERROR_LOG: A system-required executable either could not be found or was not executable by this user in file ess_singleton_module.c at line 231
[RED-GOD-UBUNTU:17390] [[INVALID],INVALID] ORTE_ERROR_LOG: A system-required executable either could not be found or was not executable by this user in file ess_singleton_module.c at line 140
[RED-GOD-UBUNTU:17390] [[INVALID],INVALID] ORTE_ERROR_LOG: A system-required executable either could not be found or was not executable by this user in file runtime/orte_init.c at line 128
--------------------------------------------------------------------------
It looks like orte_init failed for some reason; your parallel process is
likely to abort.  There are many reasons that a parallel process can
fail during orte_init; some of which are due to configuration or
environment problems.  This failure appears to be an internal failure;
here's some additional information (which may only be relevant to an
Open MPI developer):

  orte_ess_set_name failed
  --> Returned value A system-required executable either could not be found or was not executable by this user (-127) instead of ORTE_SUCCESS
--------------------------------------------------------------------------
--------------------------------------------------------------------------
It looks like MPI_INIT failed for some reason; your parallel process is
likely to abort.  There are many reasons that a parallel process can
fail during MPI_INIT; some of which are due to configuration or environment
problems.  This failure appears to be an internal failure; here's some
additional information (which may only be relevant to an Open MPI
developer):

  ompi_mpi_init: orte_init failed
  --> Returned "A system-required executable either could not be found or was not executable by this user" (-127) instead of "Success" (0)
--------------------------------------------------------------------------
[RED-GOD-UBUNTU:17390] *** An error occurred in MPI_Init
[RED-GOD-UBUNTU:17390] *** on a NULL communicator
[RED-GOD-UBUNTU:17390] *** Unknown error
[RED-GOD-UBUNTU:17390] *** MPI_ERRORS_ARE_FATAL: your MPI job will now abort
--------------------------------------------------------------------------
An MPI process is aborting at a time when it cannot guarantee that all
of its peer processes in the job will be killed properly.  You should
double check that everything has shut down cleanly.

  Reason:     Before MPI_INIT completed
  Local host: RED-GOD-UBUNTU
  PID:        17390
--------------------------------------------------------------------------`

```
