### ISSUE TITLE
Juicer: ImportError: No module named _backend_gdk

### ISSUE THREAD

**Issue by aaegea** [vterron/lemon#94]
Hello,

I get this error trying to run juicer:

	MBPdeAlllerEgea:MOSAIC Alba$ lemon juicer GLMP-diff.LEMONdb
	2017-03-22 10:11:58.239 python[20587:377990] *** WARNING: Method userSpaceScaleFactor in class NSView is deprecated on 10.7 and later. It should not be used in new applications. Use convertRectToBacking: instead. 
	Traceback (most recent call last):
	  File "/Users/Alba/lemon/lemon", line 116, in <module>
	    import juicer.main
	  File "/Users/Alba/lemon/juicer/main.py", line 21, in <module>
	    import app
	  File "/Users/Alba/lemon/juicer/app.py", line 43, in <module>
	    from matplotlib.backends.backend_gtkagg \
	  File "//anaconda/lib/python2.7/site-packages/matplotlib/backends/backend_gtkagg.py", line 14, in <module>
	    from matplotlib.backends.backend_gtk import gtk, FigureManagerGTK, FigureCanvasGTK,\
	  File "//anaconda/lib/python2.7/site-packages/matplotlib/backends/backend_gtk.py", line 36, in <module>
	    from matplotlib.backends.backend_gdk import RendererGDK, FigureCanvasGDK
	  File "//anaconda/lib/python2.7/site-packages/matplotlib/backends/backend_gdk.py", line 33, in <module>
	    from matplotlib.backends._backend_gdk import pixbuf_get_pixels_array
	ImportError: No module named _backend_gdk

I have read that it could be because my installation of matplotlib does not have gtk support compiled, but I installed python with anaconda... any suggestions ?  

Thanks!

**Comment by vterron** [comment]
Yeah, that problem is not related to `juicer` itself, and happens because your matplotlib installation [doesn't have that C extension installed](http://stackoverflow.com/questions/14346090/importerror-no-module-named-backend-gdk). In systems such as Ubuntu / Debian it would be as simple as running `apt-get install python-gtk2-dev`. I have close to zero experience with Mac Os and know even less about Anaconda. Maybe something like [this thread](https://groups.google.com/a/continuum.io/forum/#!topic/anaconda/n-F2IYyzZDs) might be of help? This is something that might be better off asked at a community of Anaconda experts.
